#!/usr/bin/env bash 

# list entries in PATH in order
show_path() {
  for d in ${PATH//:/ } ; do
    echo "$d"
  done
  echo
}
export show_path

# remove duplicates from PATH, maintaing order
dedupe_path() {
  PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
}
